### ISSUE TITLE
CouchDb views adjustment

### ISSUE THREAD

**Issue by T1m1** [locator-kn/ark-trip#13]
- [1] do not show old trips [view]
- [2] add createdate
- [3] city route /data/cities/trips -> /data/cities
  -- query_name -> city_id
- [4] limit data of get trips

**Comment by T1m1** [comment]
http://wiki.apache.org/couchdb/Document_Update_Handlers

usage, maybe for timestamp.. but you have to use _update method..

**Comment by T1m1** [comment]
[3] done

**Comment by T1m1** [comment]
[1] done

**Comment by T1m1** [comment]
[4] done

**Comment by SteffenGorenflo** [comment]
@T1m1 done?

**Comment by T1m1** [comment]
done
