### ISSUE TITLE
User account useless after creation of a trip

### ISSUE THREAD

**Issue by T1m1** [locator-kn/ark-trip#22]
Situation: I tried to create a new trip on our webpage. After I saved the trip, I was not able to login with my account anymore.

Notes: After I analysed our database, I found my account. But now, It is a database entry of type 'trip' and not of type 'user'. You can find it here: http://locator.in.htwg-konstanz.de:5984/_utils/document.html?app/ed5ad22e5fc3cb76148be1935fdb1e82

Possible solution: 
- We send the userId from frontend to backend instead of tripId
- we read the userId from session and use it as tripId
- ?

**Comment by timoweiss** [comment]
Fixed: https://github.com/locator-kn/ark-trip/commit/5387c720a5714a8e0c996dbff07a6b7d676b0c68
