### ISSUE TITLE
Validate that the provided param ID of a trip represents really a trip document in the database

### ISSUE THREAD

**Issue by SteffenGorenflo** [locator-kn/ark-trip#25]
Example: PUT /trips/:tripID gets called .But tripID represents actually a user in the database. If we don't fix this, we must be extremly careful what we send back from the frontend...

**Comment by T1m1** [comment]
Is this case possible? If we call PUT trips.. we have a joi validation to check if type='trip', or not?

If not, we can use the update handler of couchdb to che k if the document type a trip.

**Comment by SteffenGorenflo** [comment]
Its done in ark-database:

https://github.com/locator-kn/ark-database/blob/trips/src/util/util.ts#L28

same problem was when deleting a trip. Needs to be adapt in other plugins
